import type { NextPage } from "next";
import Footer from "../components/Footer";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nathan Luong</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
      <Footer />
    </div>
  );
};

export default Home;
